# Generated by Django 5.0.1 on 2025-11-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Tên sản phẩm")),
                (
                    "unit",
                    models.CharField(
                        default="kg", max_length=50, verbose_name="Đơn vị"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="Giá"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/",
                        verbose_name="Hình ảnh",
                    ),
                ),
                (
                    "in_stock",
                    models.BooleanField(default=True, verbose_name="Còn hàng"),
                ),
            ],
            options={
                "verbose_name": "Sản phẩm",
                "verbose_name_plural": "Sản phẩm",
                "db_table": "products",
                "indexes": [
                    models.Index(fields=["name"], name="products_name_6f9890_idx")
                ],
            },
        ),
    ]
