# Generated by Django 5.0.1 on 2025-11-06 11:15

import apps.orders.models.order
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "order_number",
                    models.CharField(
                        default=apps.orders.models.order.generate_order_number,
                        help_text="VD: Đơn 1, Đơn 2, Đơn 3 (reset mỗi ngày)",
                        max_length=50,
                        verbose_name="Số đơn hàng (tự động theo ngày)",
                    ),
                ),
                (
                    "order_name",
                    models.CharField(
                        help_text="Tên đơn hàng tự đặt (có thể trùng)",
                        max_length=255,
                        verbose_name="Tên đơn hàng",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=255, verbose_name="Tên khách hàng"),
                ),
                (
                    "customer_phone",
                    models.CharField(max_length=15, verbose_name="Số điện thoại"),
                ),
                (
                    "customer_address",
                    models.TextField(verbose_name="Địa chỉ giao hàng"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Tạo đơn"),
                            ("weighing", "Cân hàng"),
                            ("create_invoice", "Tạo phiếu ĐH"),
                            ("send_photo", "Gửi ảnh cân"),
                            ("payment", "Thanh toán"),
                            ("in_kitchen", "Vào bếp"),
                            ("processing", "Chế biến"),
                            ("delivery", "Giao hàng"),
                            ("completed", "Hoàn thành"),
                            ("failed", "Thất bại"),
                        ],
                        default="created",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Thời gian chuyển trạng thái",
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deadline"
                    ),
                ),
                (
                    "delivery_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Thời gian giao hàng"
                    ),
                ),
                (
                    "received_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Thời gian nhận hàng"
                    ),
                ),
                (
                    "kitchen_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Thời gian vào bếp"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="Tổng tiền sản phẩm",
                    ),
                ),
                (
                    "shipping_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="Phí ship",
                    ),
                ),
                (
                    "chip_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="Phí chip/đóng gói",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="Tổng tiền",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Ghi chú")),
                (
                    "failure_reason",
                    models.TextField(blank=True, verbose_name="Lý do thất bại"),
                ),
            ],
            options={
                "verbose_name": "Đơn hàng",
                "verbose_name_plural": "Đơn hàng",
                "db_table": "orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("status_change", "Thay đổi trạng thái"),
                            ("created", "Tạo đơn hàng"),
                            ("updated", "Cập nhật thông tin"),
                            ("image_uploaded", "Upload ảnh"),
                            ("image_deleted", "Xóa ảnh"),
                            ("comment", "Thêm ghi chú"),
                        ],
                        max_length=50,
                        verbose_name="Loại hoạt động",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Mô tả chi tiết hoạt động", verbose_name="Mô tả"
                    ),
                ),
                (
                    "old_value",
                    models.TextField(blank=True, null=True, verbose_name="Giá trị cũ"),
                ),
                (
                    "new_value",
                    models.TextField(blank=True, null=True, verbose_name="Giá trị mới"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Dữ liệu JSON bổ sung về hoạt động",
                        null=True,
                        verbose_name="Dữ liệu bổ sung",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Thời gian"),
                ),
            ],
            options={
                "verbose_name": "Lịch sử đơn hàng",
                "verbose_name_plural": "Lịch sử đơn hàng",
                "db_table": "order_activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="order_comments/%Y/%m/%d/"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_edited", models.BooleanField(default=False)),
                (
                    "is_system_message",
                    models.BooleanField(
                        default=False,
                        help_text="System-generated message (e.g., 'Order status changed')",
                    ),
                ),
            ],
            options={
                "db_table": "order_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderCommentReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[
                            ("like", "👍 Like"),
                            ("heart", "❤️ Heart"),
                            ("check", "✅ Check"),
                        ],
                        default="like",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "order_comment_reactions",
            },
        ),
        migrations.CreateModel(
            name="OrderImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="orders/%Y/%m/%d/", verbose_name="Hình ảnh"
                    ),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("weighing", "Ảnh cân hàng"),
                            ("invoice", "Ảnh phiếu đặt hàng"),
                            ("other", "Khác"),
                        ],
                        max_length=20,
                        verbose_name="Loại ảnh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hình ảnh đơn hàng",
                "verbose_name_plural": "Hình ảnh đơn hàng",
                "db_table": "order_images",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "product_name",
                    models.CharField(max_length=255, verbose_name="Tên sản phẩm"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Số lượng"
                    ),
                ),
                ("unit", models.CharField(max_length=50, verbose_name="Đơn vị")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="Giá"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="Thành tiền"
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, default="", verbose_name="Ghi chú món"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sản phẩm đơn hàng",
                "verbose_name_plural": "Sản phẩm đơn hàng",
                "db_table": "order_items",
            },
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "from_status",
                    models.CharField(max_length=20, verbose_name="Trạng thái cũ"),
                ),
                (
                    "to_status",
                    models.CharField(max_length=20, verbose_name="Trạng thái mới"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Ghi chú")),
            ],
            options={
                "verbose_name": "Lịch sử trạng thái",
                "verbose_name_plural": "Lịch sử trạng thái",
                "db_table": "order_status_history",
                "ordering": ["-created_at"],
            },
        ),
    ]
