# Generated by Django 5.0.1 on 2025-10-30 13:58

import apps.orders.models.order
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "order_number",
                    models.CharField(
                        default=apps.orders.models.order.generate_order_number,
                        max_length=50,
                        unique=True,
                        verbose_name="Số đơn hàng",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=255, verbose_name="Tên khách hàng"),
                ),
                (
                    "customer_phone",
                    models.CharField(max_length=15, verbose_name="Số điện thoại"),
                ),
                (
                    "customer_address",
                    models.TextField(verbose_name="Địa chỉ giao hàng"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Tạo đơn"),
                            ("weighing", "Cân hàng"),
                            ("create_invoice", "Tạo phiếu ĐH"),
                            ("send_photo", "Gửi ảnh cân"),
                            ("payment", "Thanh toán"),
                            ("in_kitchen", "Vào bếp"),
                            ("completed", "Hoàn thành"),
                            ("failed", "Thất bại"),
                        ],
                        default="created",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Thời gian chuyển trạng thái",
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deadline"
                    ),
                ),
                (
                    "delivery_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Thời gian giao hàng"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="Tổng tiền sản phẩm",
                    ),
                ),
                (
                    "shipping_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="Phí ship",
                    ),
                ),
                (
                    "chip_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="Phí chip/đóng gói",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="Tổng tiền",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Ghi chú")),
                (
                    "failure_reason",
                    models.TextField(blank=True, verbose_name="Lý do thất bại"),
                ),
                (
                    "assigned_to",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người phụ trách",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người tạo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Đơn hàng",
                "verbose_name_plural": "Đơn hàng",
                "db_table": "orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="orders/%Y/%m/%d/", verbose_name="Hình ảnh"
                    ),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("weighing", "Ảnh cân hàng"),
                            ("invoice", "Ảnh phiếu đặt hàng"),
                            ("other", "Khác"),
                        ],
                        max_length=20,
                        verbose_name="Loại ảnh",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="orders.order",
                        verbose_name="Đơn hàng",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người upload",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hình ảnh đơn hàng",
                "verbose_name_plural": "Hình ảnh đơn hàng",
                "db_table": "order_images",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "product_name",
                    models.CharField(max_length=255, verbose_name="Tên sản phẩm"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Số lượng"
                    ),
                ),
                ("unit", models.CharField(max_length=50, verbose_name="Đơn vị")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="Giá"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="Thành tiền"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="Đơn hàng",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.product",
                        verbose_name="Sản phẩm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sản phẩm đơn hàng",
                "verbose_name_plural": "Sản phẩm đơn hàng",
                "db_table": "order_items",
            },
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "from_status",
                    models.CharField(max_length=20, verbose_name="Trạng thái cũ"),
                ),
                (
                    "to_status",
                    models.CharField(max_length=20, verbose_name="Trạng thái mới"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Ghi chú")),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người thay đổi",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="orders.order",
                        verbose_name="Đơn hàng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lịch sử trạng thái",
                "verbose_name_plural": "Lịch sử trạng thái",
                "db_table": "order_status_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_number"], name="orders_order_n_1336be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="orders_status_762191_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["-created_at"], name="orders_created_b25042_idx"
            ),
        ),
    ]
