# Generated by Django 5.0.1 on 2025-11-06 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người phụ trách",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người tạo",
            ),
        ),
        migrations.AddField(
            model_name="orderactivity",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="orders.order",
                verbose_name="Đơn hàng",
            ),
        ),
        migrations.AddField(
            model_name="orderactivity",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_activities",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người thực hiện",
            ),
        ),
        migrations.AddField(
            model_name="ordercomment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="ordercomment",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ordercommentreaction",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="orders.ordercomment",
            ),
        ),
        migrations.AddField(
            model_name="ordercommentreaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_reactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderimage",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="orders.order",
                verbose_name="Đơn hàng",
            ),
        ),
        migrations.AddField(
            model_name="orderimage",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người upload",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.order",
                verbose_name="Đơn hàng",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="products.product",
                verbose_name="Sản phẩm",
            ),
        ),
        migrations.AddField(
            model_name="orderstatushistory",
            name="changed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người thay đổi",
            ),
        ),
        migrations.AddField(
            model_name="orderstatushistory",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="orders.order",
                verbose_name="Đơn hàng",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_number"], name="orders_order_n_1336be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["order_name"], name="orders_order_n_a1d48e_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="orders_status_762191_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["-created_at"], name="orders_created_b25042_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["delivery_time"], name="orders_deliver_89a875_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderactivity",
            index=models.Index(
                fields=["order", "-created_at"], name="order_activ_order_i_ca3e0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderactivity",
            index=models.Index(
                fields=["activity_type"], name="order_activ_activit_057368_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ordercomment",
            index=models.Index(
                fields=["order", "created_at"], name="order_comme_order_i_29f41c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ordercomment",
            index=models.Index(
                fields=["user", "created_at"], name="order_comme_user_id_6e0222_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ordercommentreaction",
            index=models.Index(
                fields=["comment", "reaction_type"],
                name="order_comme_comment_10ecfb_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ordercommentreaction",
            unique_together={("comment", "user", "reaction_type")},
        ),
    ]
