# Generated by Django 5.0.1 on 2025-10-31 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Tạo đơn'), ('weighing', 'Cân hàng'), ('create_invoice', 'Tạo phiếu ĐH'), ('send_photo', 'Gửi ảnh cân'), ('payment', 'Thanh toán'), ('in_kitchen', 'Vào bếp'), ('processing', 'Chế biến'), ('delivery', 'Giao hàng'), ('completed', 'Hoàn thành'), ('failed', 'Thất bại')], default='created', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.CreateModel(
            name='OrderActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('status_change', 'Thay đổi trạng thái'), ('created', 'Tạo đơn hàng'), ('updated', 'Cập nhật thông tin'), ('image_uploaded', 'Upload ảnh'), ('image_deleted', 'Xóa ảnh'), ('comment', 'Thêm ghi chú')], max_length=50, verbose_name='Loại hoạt động')),
                ('description', models.TextField(help_text='Mô tả chi tiết hoạt động', verbose_name='Mô tả')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Giá trị cũ')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='Giá trị mới')),
                ('metadata', models.JSONField(blank=True, help_text='Dữ liệu JSON bổ sung về hoạt động', null=True, verbose_name='Dữ liệu bổ sung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='orders.order', verbose_name='Đơn hàng')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_activities', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
            ],
            options={
                'verbose_name': 'Lịch sử đơn hàng',
                'verbose_name_plural': 'Lịch sử đơn hàng',
                'db_table': 'order_activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', '-created_at'], name='order_activ_order_i_ca3e0d_idx'), models.Index(fields=['activity_type'], name='order_activ_activit_057368_idx')],
            },
        ),
    ]
