# Generated by Django 5.0.1 on 2025-10-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Tên khách hàng"),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="Số điện thoại"
                    ),
                ),
                ("address", models.TextField(verbose_name="Địa chỉ")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Ghi chú")),
                (
                    "is_vip",
                    models.BooleanField(default=False, verbose_name="Khách VIP"),
                ),
            ],
            options={
                "verbose_name": "Khách hàng",
                "verbose_name_plural": "Khách hàng",
                "db_table": "customers",
                "indexes": [
                    models.Index(fields=["phone"], name="customers_phone_91048b_idx"),
                    models.Index(fields=["name"], name="customers_name_25d5e3_idx"),
                ],
            },
        ),
    ]
