# Generated by Django 5.0.1 on 2025-10-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Quản trị viên'), ('manager', 'Quản lý'), ('sale', 'Nhân viên bán hàng'), ('weighing', 'Bộ phận cân hàng'), ('kitchen', 'Bộ phận bếp')], default='sale', max_length=20, verbose_name='Vai trò'),
        ),
    ]
